import type { NextPage } from 'next'
import { IPost } from '../interfaces'
import Head from 'next/head'
import { Navbar } from '../layouts/Navbar'
import { Wrapper, PostItems, Post, Title } from '../styles/GlobalStyled'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import axios from 'axios'
import Link from 'next/link'

export const getStaticProps: GetStaticProps = async () => {
  const getPosts = await (await axios('http://localhost:8080/api/post')).data
  return {
    props: {
      getPosts,
    },
  }
}
const Home: NextPage = ({
  getPosts,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Navbar />
      <Wrapper>
        <div className='container'>
          <PostItems>
            {getPosts.map((post: IPost, idx: number) => (
              <Link href={'/post/[id]'} as={`/post/${post._id}`} key={idx}>
                <Post img={post.image}>
                  <Title>{post.title}</Title>
                </Post>
              </Link>
            ))}
          </PostItems>
        </div>
      </Wrapper>
    </div>
  )
}

export default Home
