import type { NextPage } from 'next'
import Image from 'next/image'
import Head from 'next/head'
import { Navbar } from '../../layouts/Navbar'
import { useRouter } from 'next/router'
import {
  BackBtn,
  PostDescr,
  PostItem,
  PostsWrapper,
  PostTitle,
  RemoveBtn,
  Wrapper,
} from '../../styles/GlobalStyled'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import axios from 'axios'

export const getServerSideProps: GetServerSideProps = async (context) => {
  const post = await (
    await axios(`http://localhost:8080/api/post/${context.query.id}`)
  ).data
  return {
    props: {
      post,
    },
  }
}

const Post: NextPage = ({
  post,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const route = useRouter()
  const removePost = async () => {
    await axios
      .post('http://localhost:8080/api/post/remove', {
        postId: post._id,
      })
      .then(() => route.push('/'))
  }
  return (
    <>
      <Head>
        <title>{post.title}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Navbar />
      <Wrapper>
        <div className='container'>
          <BackBtn onClick={() => route.push('/')}>
            <Image
              src='/static/images/Vector.svg'
              alt='Picture of the author'
              width={24}
              height={15}
            />
            Назад
          </BackBtn>
          <PostsWrapper>
            <PostItem>
              <PostTitle>{post?.title}</PostTitle>
              <PostDescr>{post?.desc}</PostDescr>
            </PostItem>
            <PostItem>
              <Image
                src={post?.image}
                alt='Picture of the author'
                width={540}
                height={316}
              />
            </PostItem>
            <RemoveBtn onClick={removePost}>Удалить статью</RemoveBtn>
          </PostsWrapper>
        </div>
      </Wrapper>
    </>
  )
}
export default Post
