import type { NextPage } from 'next'
import { IPost } from '../interfaces'
import Head from 'next/head'
import { Navbar } from '../layouts/Navbar'
import { Wrapper, PostItems, Post, Title,Container } from '../styles/components'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import axios from 'axios'
import Link from 'next/link'

export const getStaticProps: GetStaticProps = async () => {
  const getPosts = await (await axios(`${process.env.REACT_APP_API_URL}/api/post`)).data
  return {
    props: {
      getPosts,
    },
  }
}
const Home: NextPage = ({
  getPosts,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const fakeArray = new Array(6).fill({
    image: 'https://двхм.рф/wp-content/uploads/2018/04/placeholder.png',
    title: 'fill me',
  })
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Navbar />
      <Wrapper>
        <Container>
          <PostItems>
            {getPosts.length === 0
              ? fakeArray.map((item, idx) => (
                  <Post img={item.image} key={idx}>
                    <Title>{item.title}</Title>
                  </Post>
                ))
              : getPosts.map((post: IPost, idx: number) => (
                  <Link href={'/post/[id]'} as={`/post/${post._id}`} key={idx}>
                    <Post img={post.image}>
                      <Title>{post.title}</Title>
                    </Post>
                  </Link>
                ))}
          </PostItems>
        </Container>
      </Wrapper>
    </div>
  )
}

export default Home
